name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable

      - name: Create .env
        run: |
          echo "USDA_API_KEY=${{ secrets.USDA_API_KEY }}" > .env

      - name: Create firebase_options.dart
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_DART }}" | base64 --decode > lib/firebase_options.dart

      - run: flutter pub get

      - run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Install Ruby dependencies
        run: |
          cd ios
          bundle install

      - name: Install signing certificates
        run: |
          cd ios
          bundle exec fastlane match appstore readonly:true

      - name: Build IPA
        run: flutter build ipa --release

      - name: Check Fastlane
        run: fastlane --version

      - name: Upload to TestFlight
        run: |
          cd ios
          fastlane beta